<p>“Здесь будет таймер, который я сделаю в другом задании”</p>

<div class="search-widget">
    <label for="abc-search-input">Search for sku: </label>
    <input type="text" name="sku-search" id="abc-search-input">
    <ul class="search-result-list"></ul>
</div>

<script type="text/x-magento-init">
   {
       ".search-widget": {
           "Amasty_Aleksandr/js/widgetAutocomplete": {
               "minChars": 3
           }
       }
   }
</script>
